server:
  port: 7005

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
    # 资源信息
  messages:
    # 国际化资源配置文件路径
    basename: i18n/message
    encoding: utf-8
  application:
    name: altxch-member